### ISSUE TITLE
erro page is shown clicking 'new entry' button

### ISSUE THREAD

**Issue by bisegni** [eed-web-application/elog-plus-frontend#49] opened 2024-01-29 23:40 UTC
on console is shown this error(@tiffany-slac added to the conversation):

```
index-8646652c.js:40 TypeError: Cannot read properties of undefined (reading 'id')
    at index-8646652c.js:140:16156
    at Array.reduce (<anonymous>)
    at EP (index-8646652c.js:140:16137)
    at Fm (index-8646652c.js:38:19518)
    at Iw (index-8646652c.js:40:44027)
    at _w (index-8646652c.js:40:39763)
    at wC (index-8646652c.js:40:39691)
    at Cu (index-8646652c.js:40:39545)
    at th (index-8646652c.js:40:35913)
    at og (index-8646652c.js:40:36716)
Hd @ index-8646652c.js:40
index-8646652c.js:59 React Router caught the following error during render TypeError: Cannot read properties of undefined (reading 'id')
    at index-8646652c.js:140:16156
    at Array.reduce (<anonymous>)
    at EP (index-8646652c.js:140:16137)
    at Fm (index-8646652c.js:38:19518)
    at Iw (index-8646652c.js:40:44027)
    at _w (index-8646652c.js:40:39763)
    at wC (index-8646652c.js:40:39691)
    at Cu (index-8646652c.js:40:39545)
    at th (index-8646652c.js:40:35913)
    at og (index-8646652c.js:40:36716) Object
```

**Comment by ocboogie** [comment] 2024-02-05 21:30
Hm, I can't reproduce under the development environment. Can you give more information about the environment this error was encounter under.

**Comment by bisegni** [comment] 2024-02-05 22:13
Hi you can check directly here: https://accel-webapp-dev.slac.stanford.edu/elog/when you are locally remember to rebuild the docker image after update the backend source code Saluti ClaudioOn Feb 5, 2024, at 1:30 PM, ocboogie ***@***.***> wrote:﻿
Hm, I can't reproduce under the development environment. Can you give more information about the environment this error was encounter under.

**Comment by ocboogie** [comment] 2024-02-12 20:59
Most likely the draft stored in the browser is outdated. Try deleting the old data by going to DevTools and
![image](https://github.com/eed-web-application/elog-plus-frontend/assets/8641243/7d449589-4ce5-469d-8a72-34e41f3ae369)

**Comment by ocboogie** [comment] 2024-02-12 21:06
Closing, in favor of #52. If the suggested fix above does not work, feel free to reopen.

**Closed by ocboogie** 2024-02-12 21:06 UTC

**Comment by bisegni** [comment] 2024-02-12 21:10
the solution worked, and i have also to refresh the page.
